### ISSUE TITLE
pep-0263 error on health check?

### ISSUE THREAD

**Issue by datakid** [PBSPro/nvidia-dcgm-pbspro-connector#6]
```
[root@host ~]# /opt/pbs/nvidia/PBS_scripts/nvidia_health_check
  File "/opt/pbs/nvidia/PBS_scripts/nvidia_health_check", line 30
SyntaxError: Non-ASCII character '\xe2' in file /opt/pbs/nvidia/PBS_scripts/nvidia_health_check on line 30, but no encoding declared; see http://www.python.org/peps/pep-0263.
html for details
```

**Comment by datakid** [comment]
Adding `# -*- coding: utf-8 -*-` at line two works, but gives a new error:
```
{"comment": "Failed to load DCGM modules", "health": "Error"}
```

**Comment by vaib** [comment]
Hey, error was because of special characters in the license text which is fixed by the utf encoding.

The other error is due to DCGM modules not being loaded. Is DCGM installed and in standard location?

**Comment by datakid** [comment]
I don't think I've installed the DCGM on the management node, because it has no GPUs on it. It's hard to tell from the DCGM documentation which instances need it installed - the management node, the GPU nodes or both

**Comment by vaib** [comment]
DCGM is the underlying layer of API that enables the connector to talk to the GPUs. Please install nvidia driver and DCGM v1.3.3+ on all GPU nodes.

**Comment by datakid** [comment]
Yep, that's what I have. I've just found that nv-hostengine is failing on the GPU nodes. So I'll look into fixing that.

**Comment by vaib** [comment]
yes, nv-hostengine needs to be running. probably a version mismatch.

**Comment by datakid** [comment]
? We are using 1.7.1 of DCGM and 418 nvidia drivers. That seems to be an acceptable standard?

**Comment by vaib** [comment]
It should. Haven't tested yet with 1.7.1 but it should work. As long as the interface hasn't changed.
