### ISSUE TITLE
Confusion about order of resource_framework_hook

### ISSUE THREAD

**Issue by datakid** [PBSPro/nvidia-dcgm-pbspro-connector#7]
I'm not an expert on hooks, but I'm confused. 

In step 7 we are asked to "Set order of resource_framework_hook higher than that of PBS_cgroups."

According to page 340 of the Resource Guide (RG-340):
```
order
Indicates relative order of hook execution, for
hooks of the same type sharing a trigger. Hooks
with lower order values execute before those with
higher values.
Does not apply to periodic or
exechost_periodic hooks.
```
But when I look at the resource_framework_hook definition I see this:

```
set hook resource_framework_hook event += exechost_periodic
```

**Comment by datakid** [comment]
I see now. there are 4 types of hooks in this hook. The order wont apply to one of them but will the other three.

**Comment by vaib** [comment]
Yes, thats right. The order is for other events.

Sent from Yahoo7 Mail on Android 
 
  On Mon, 20 Apr 2020 at 1:57 pm, Lachlan Musicman<notifications@github.com> wrote:   


I'm not an expert on hooks, but I'm confused.

In step 7 we are asked to "Set order of resource_framework_hook higher than that of PBS_cgroups."

According to page 340 of the Resource Guide (RG-340):
order
Indicates relative order of hook execution, for
hooks of the same type sharing a trigger. Hooks
with lower order values execute before those with
higher values.
Does not apply to periodic or
exechost_periodic hooks.

But when I look at the resource_framework_hook definition I see this:
set hook resource_framework_hook event += exechost_periodic
